apiVersion: batch/v1
kind: Job
metadata:
  name: efficient-fibonacci
spec:
  template:
    spec:
      containers:
      - name: efficient-fibonacci
        image: efficient-fibonacci:latest
        imagePullPolicy: Never
        env:
        - name: INPUT
          value: "995"
      restartPolicy: Never
